name: actionlint
on:
  workflow_call:
    inputs:
      actionlint_options:
        required: false
        type: string
        description: |
          actionlint's command line options such as `-ignore`.
      sparse-checkout:
        required: false
        type: string
        description: |
          sparse checkout
      path-filters:
        required: false
        type: string
        description: |
          path filters.
permissions: {}
jobs:
  path-filter:
    timeout-minutes: 10
    outputs:
      value: ${{steps.changes.outputs.value}}
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            value:
              - .github/workflows/*.yml
              - .github/workflows/*.yaml
              ${{inputs.path-filters}}

  main:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    needs: path-filter
    if: needs.path-filter.outputs.value == 'true'
    permissions:
      pull-requests: write # For reviewdog
      contents: read # For checkout private repository
    steps:
      - uses: suzuki-shunsuke/actionlint-action@cf6cff1c6bffd4a4c8a15db39a3a5870057d1946 # v0.0.2
        with:
          sparse-checkout: ${{inputs.sparse-checkout}}
          actionlint_options: ${{inputs.actionlint_options}}
        env:
          AQUA_LOG_COLOR: always
