name: actionlint
on:
  workflow_call:
    inputs:
      aqua_policy_allow:
        required: false
        type: string
      aqua_policy_config:
        required: false
        type: string
      aqua_version:
        required: true
        type: string
      runs-on:
        required: false
        type: string
        default: '"ubuntu-latest"'
        description: |
          JSON string for runs-on.
          e.g.
          runs-on: '"macos-latest"'
          runs-on: '["foo"]'

permissions: {}

env:
  AQUA_POLICY_CONFIG: ${{inputs.aqua_policy_config}}
  AQUA_LOG_COLOR: always
  AQUA_DISABLE_COSIGN: "true"

jobs:
  actionlint:
    runs-on: ${{fromJSON(inputs.runs-on)}}
    permissions:
      pull-requests: write # For reviewdog
      contents: read # For checkout private repository
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: aquaproj/aqua-installer@7c7338067bdb97d5bea2acc82b5870afca470d18 # v2.3.0
        with:
          aqua_version: ${{inputs.aqua_version}}
          policy_allow: ${{inputs.aqua_policy_allow}}
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - uses: suzuki-shunsuke/github-action-actionlint@60449a33b52da4f92a069b8af50d04515d6177bf # v0.1.3
        if: |
          github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork
      - run: actionlint
        if: |
          github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
