name: actionlint
on:
  workflow_call:
    inputs:
      aqua_policy_allow:
        required: false
        type: string
      aqua_policy_config:
        required: false
        type: string
      aqua_version:
        required: true
        type: string
      runs-on:
        required: false
        type: string
        default: '"ubuntu-latest"'
        description: |
          JSON string for runs-on.
          e.g.
          runs-on: '"macos-latest"'
          runs-on: '["foo"]'
      actionlint_options:
        required: false
        type: string
        description: |
          actionlint's command line options such as `-ignore`.
      sparse-checkout:
        required: false
        type: string
        description: |
          sparse checkout

permissions: {}

env:
  AQUA_POLICY_CONFIG: ${{inputs.aqua_policy_config}}
  AQUA_LOG_COLOR: always

jobs:
  actionlint:
    timeout-minutes: 30
    runs-on: ${{fromJSON(inputs.runs-on)}}
    permissions:
      pull-requests: write # For reviewdog
      contents: read # For checkout private repository
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: ${{inputs.sparse-checkout}}
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: ${{inputs.aqua_version}}
          policy_allow: ${{inputs.aqua_policy_allow}}
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - uses: suzuki-shunsuke/github-action-actionlint@60449a33b52da4f92a069b8af50d04515d6177bf # v0.1.3
        if: |
          github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork
        with:
          actionlint_options: ${{inputs.actionlint_options}}
      - run: |
          set -euo pipefail
          # shellcheck disable=SC2086
          actionlint $ACTIONLINT_OPTIONS
        if: |
          github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
          ACTIONLINT_OPTIONS: ${{inputs.actionlint_options}}
