name: actionlint
on:
  workflow_call:
    inputs:
      aqua_policy_allow:
        required: false
        type: string
      aqua_policy_config:
        required: false
        type: string
      aqua_version:
        required: true
        type: string
      runs-on:
        required: false
        type: string
        default: '"ubuntu-latest"'
        description: |
          JSON string for runs-on.
          e.g.
          runs-on: '"macos-latest"'
          runs-on: '["foo"]'
      actionlint_options:
        required: false
        type: string
        description: |
          actionlint's command line options such as `-ignore`.

permissions: {}

env:
  AQUA_POLICY_CONFIG: ${{inputs.aqua_policy_config}}
  AQUA_LOG_COLOR: always

jobs:
  actionlint:
    runs-on: ${{fromJSON(inputs.runs-on)}}
    permissions:
      pull-requests: write # For reviewdog
      contents: read # For checkout private repository
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: aquaproj/aqua-installer@36dc5833b04eb63f06e3bb818aa6b7a6e6db99a9 # v2.1.2
        with:
          aqua_version: ${{inputs.aqua_version}}
          policy_allow: ${{inputs.aqua_policy_allow}}
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - uses: suzuki-shunsuke/github-action-actionlint@60449a33b52da4f92a069b8af50d04515d6177bf # v0.1.3
        if: |
          github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork
        with:
          actionlint_options: ${{inputs.actionlint_options}}
      - run: |
          set -euo pipefail
          # shellcheck disable=SC2086
          actionlint $ACTIONLINT_OPTIONS
        if: |
          github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
          ACTIONLINT_OPTIONS: ${{inputs.actionlint_options}}
