---
name: actionlint for fork

on:
  workflow_call:
    inputs:
      aqua_policy_config:
        required: false
        type: string
      aqua_version:
        required: true
        type: string

env:
  AQUA_POLICY_CONFIG: ${{inputs.aqua_policy_config}}
  AQUA_LOG_COLOR: always

permissions: {}

jobs:
  actionlint_fork:
    if: github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: aquaproj/aqua-installer@61e2563dfe7674cbf74fe6ec212e444198a3bb00 # v2.0.2
        with:
          aqua_version: ${{inputs.aqua_version}}
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: actionlint
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
