name: actionlint
on: workflow_call

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # For reviewdog
      contents: read # For checkout private repository
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
    - uses: aquaproj/aqua-installer@61e2563dfe7674cbf74fe6ec212e444198a3bb00 # v2.0.2
      with:
        aqua_version: v1.31.0
    - uses: suzuki-shunsuke/github-action-actionlint@764a394381fb91f87ca8a8ad022bbeb49232df8b # v0.1.2
