name: actionlint
on:
  workflow_call:
    inputs:
      aqua_policy_allow:
        required: false
        type: string
      aqua_policy_config:
        required: false
        type: string
      aqua_version:
        required: true
        type: string
      runs-on:
        required: false
        type: string
        default: '"ubuntu-latest"'
        description: |
          JSON string for runs-on.
          e.g.
          runs-on: '"macos-latest"'
          runs-on: '["foo"]'

permissions: {}

env:
  AQUA_POLICY_CONFIG: ${{inputs.aqua_policy_config}}
  AQUA_LOG_COLOR: always

jobs:
  actionlint:
    runs-on: ${{fromJSON(inputs.runs-on)}}
    permissions:
      pull-requests: write # For reviewdog
      contents: read # For checkout private repository
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: aquaproj/aqua-installer@294926f94b4233f202a2f03875c604f840cfed70 # v2.1.1
        with:
          aqua_version: ${{inputs.aqua_version}}
          policy_allow: ${{inputs.aqua_policy_allow}}
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - uses: suzuki-shunsuke/github-action-actionlint@764a394381fb91f87ca8a8ad022bbeb49232df8b # v0.1.2
        if: |
          github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork
      - run: actionlint
        if: |
          github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
