---
name: test
on: pull_request
permissions: {}
jobs:
  path-filter:
    # Get changed files to filter jobs
    timeout-minutes: 10
    outputs:
      update-aqua-checksums: ${{steps.changes.outputs.update-aqua-checksums}}
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
      ghalint: ${{steps.changes.outputs.ghalint}}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read # To get pull requests of private repository
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            update-aqua-checksums:
              - aqua/aqua.yaml
              - aqua/imports/*.yaml
              - aqua/aqua-checksums.json
              - .github/workflows/wc-update-aqua-checksums.yaml
              - .github/workflows/test.yaml
            renovate-config-validator:
              - renovate.json5
              - .github/workflows/wc-renovate-config-validator.yaml
              - .github/workflows/test.yaml
            ghalint:
              - .github/workflows/*.yaml
              - aqua/imports/ghalint.yaml

  renovate-config-validator:
    uses: ./.github/workflows/wc-renovate-config-validator.yaml
    needs: path-filter
    if: needs.path-filter.outputs.renovate-config-validator == 'true'
    permissions:
      contents: read

  ghalint:
    needs: path-filter
    if: needs.path-filter.outputs.ghalint == 'true'
    uses: ./.github/workflows/wc-ghalint.yaml
    permissions:
      contents: read

  update-aqua-checksums:
    needs: path-filter
    if: needs.path-filter.outputs.update-aqua-checksums == 'true'
    uses: ./.github/workflows/wc-update-aqua-checksums.yaml
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
    permissions:
      contents: read

  test:
    uses: ./.github/workflows/actionlint.yaml
    permissions:
      contents: read
      pull-requests: write # For reviewdog
