---
name: test

on: pull_request

permissions: {}

jobs:
  test:
    uses: ./.github/workflows/actionlint.yaml
    permissions:
      contents: read
      pull-requests: write # For reviewdog
    with:
      aqua_version: v2.9.0
