---
name: Enable Automerge of a pull request from Renovate

on:
  workflow_call:
    secrets:
      gh_app_id:
        required: false
      gh_app_private_key:
        required: false

jobs:
  enable_automerge:
    uses: suzuki-shunsuke/renovate-enable-automerge-workflow/.github/workflows/enable_automerge.yaml@feat/first-pr
    permissions: {}
    with:
      merge_method: squash
    secrets:
      gh_app_id: ${{secrets.gh_app_id}}
      gh_app_private_key: ${{secrets.gh_app_private_key}}
