---
name: Enable Automerge of a pull request from Renovate

on:
  workflow_call:
    secrets:
      gh_app_id:
        required: false
      gh_app_private_key:
        required: false

jobs:
  enable-auto-merge:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: suzuki-shunsuke/enable-auto-merge-action@feat/first-pr
        with:
          pr_number: ${{github.event.pull_request.number}}
          merge_method: squash
          gh_app_id: ${{secrets.gh_app_id}}
          gh_app_private_key: ${{secrets.gh_app_private_key}}
